sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script:
- pdflatex -interaction=nonstopmode -halt-on-error rules.tex
deploy:
  provider: releases
  api_key:
    secure: Y0e8TT7PvDOn/W0xWfaTrSpGEQeYKUCHguS0m/T08m9ll3AiSvuxko8llu7YxJRZ/F1hqYxz3TaWVDbC1GmbbIyAEG049SZo3HOIBCcYrni2vcgOIq9S+dT5kHDhnCd14uDzEPfpux3h+toeDKCT/ZbKXDh2PcZZdBopb6P/43BUxMAGtHJpiX4uHf1T+8aT5Zjvz5Y4TsVECXUQG6trM/nRhrLoAUVNws4ChIEkS/ouF+7TZth0wzDFqjpWrQ+5jDNU2g+crkMgFOQB9Pe/KDA2Ku1L+bWy4e8PufOrcGk7VltkohXJD4yiMCMrJ3C14LJcCI+vtsarPiEpmGO8uC6YLilfc1aweKHAwnfne8DElvJ5zhq4bboe7VJiZroDUCaZaegrcwR4VyeLIClrZ7rWnONWbUQrOZpBK5JrdMUXmjJP4aDW/U4alZaETWoEDnUFLF6QEebeZYM3y6fIe6eY7XBXSumfWFLR9lm5WDZQ3iezTHuA1hPEN7K5iLG9avnYmT0D79knT/FBRzPfpScPe2o182VS0ZgcH2fMQtQLxJ8wXewY55hqdiZ4aDBNDqzlf6ZMJnb84+Do/zrDHJqYJwqpdpPFDvhNBMLwPFoCI96/R8fFXocTJG8ouAnN8AFyTDSbrsmXQy7mQRT8xI3lKeAXjk5EGixKkN5wvTc=
  file: rules.pdf
  skip_cleanup: true
  on:
    repo: Magelfik/regles-serv-mc-2018
notifications:
  webhooks: http://serv.magelfik.ch/notifiy-rules-change.php
